# Generated by Django 3.1.4 on 2020-12-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewPodcastState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_subscribes', models.CharField(default=True, max_length=120)),
                ('new_plays', models.CharField(default=True, max_length=120)),
                ('date', models.CharField(default=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=30)),
                ('url', models.CharField(default=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TotalPodcastState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=30)),
                ('total_subscribed', models.CharField(default=True, max_length=30)),
                ('total_played', models.CharField(default=True, max_length=120)),
                ('date', models.CharField(default=True, max_length=120)),
            ],
        ),
    ]
