# Generated by Django 2.2.5 on 2020-12-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalpodcaststate',
            name='reference_key',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='totalpodcaststate',
            name='date',
            field=models.CharField(blank=True, default=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='totalpodcaststate',
            name='name',
            field=models.CharField(blank=True, default=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='totalpodcaststate',
            name='total_played',
            field=models.CharField(blank=True, default=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='totalpodcaststate',
            name='total_subscribed',
            field=models.CharField(blank=True, default=True, max_length=30, null=True),
        ),
    ]
