# Generated by Django 2.2.5 on 2020-12-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_app', '0002_auto_20201207_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalpodcaststate',
            name='new_plays',
            field=models.CharField(blank=True, default=True, max_length=120),
        ),
        migrations.AddField(
            model_name='totalpodcaststate',
            name='new_subscribes',
            field=models.CharField(blank=True, default=True, max_length=120),
        ),
    ]
