# Generated by Django 2.2.5 on 2020-12-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_app', '0005_auto_20201209_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalpodcaststate',
            name='total_subscribed',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
    ]
