# Generated by Django 2.2.5 on 2020-12-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_app', '0006_auto_20201210_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalpodcaststate',
            name='new_plays',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='totalpodcaststate',
            name='new_subscribes',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='totalpodcaststate',
            name='reference_key',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='totalpodcaststate',
            name='total_played',
            field=models.IntegerField(blank=True, default=True),
        ),
    ]
