# Generated by Django 2.2.5 on 2020-12-11 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_app', '0007_auto_20201210_1915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewPodcastState',
        ),
        migrations.RemoveField(
            model_name='totalpodcaststate',
            name='reference_key',
        ),
    ]
