# Generated by Django 2.2.5 on 2020-12-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_app', '0008_auto_20201211_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalpodcaststate',
            name='date',
            field=models.DateTimeField(blank=True, default=True, null=True),
        ),
    ]
