# Generated by Django 2.2.5 on 2020-12-11 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_app', '0009_auto_20201211_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalpodcaststate',
            name='newpodcast',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='podcast_app.Podcast'),
        ),
    ]
